In [4]:
import pandas as pd

In [9]:
a = pd.read_csv("mat.csv", header = None)
a

,0,1,2,3,4,5,6,7,8,9,...,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,0,1,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,1,1,0,1,1,0,1,...,0,0,1,1,0,0,1,0,1,1
3,0,1,0,0,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,0,0,0,0,1,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
793,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
794,1,1,1,1,1,1,1,0,1,1,...,0,0,0,0,0,0,0,0,1,0
795,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
796,0,0,0,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
with open('rowZip.csv', 'r') as file:
    rows = file.readlines()
rows = [[int(st) for st in row.split(',')] for row in rows]
rows[0]

[12, 42, 170, 186, 216, 439, 461, 476, 493, 540, 547, 566, 605, 755, 794]

In [8]:
with open('colZip.csv', 'r') as file:
    cols = file.readlines()
cols = [[int(st) for st in col.split(',')] for col in cols]
cols[0]

[0,
 4,
 5,
 8,
 10,
 13,
 18,
 19,
 23,
 26,
 32,
 35,
 36,
 37,
 51,
 58,
 60,
 66,
 82,
 99,
 110,
 136,
 253]

In [16]:
pick = 357
for i in rows[pick]:
    for j in cols[pick]:
        if a.iloc[i][j] == 0:
            print('illegal')